[project]
name = "nldisco"
version = "0.1.0"
description = "Neural latent discovery with sparse encoder-decoder models"
authors = [{ name = "Jai Bhagat", email = "jkbhagatio@gmail.com" }]
readme = "readme.md"
requires-python = ">=3.9,<3.10"
dependencies = [
    "allensdk>=2.16",
    "brainsets==0.1.2",
    "cebra==0.4.0",
    "dandi",
    "datasets>=2.14.6",
    "einops",
    "email-validator",
    "h5py",
    "huggingface-hub",
    "ipython",
    "ipywidgets",
    "jax>=0.4.21",
    "jaxtyping",
    "matplotlib",
    "numpy<1.24",
    "openai",
    "pandas==1.5.3",
    "plotly>=5.23,<6",
    "requests",
    "rich",
    "scikit-learn==1.5.2",
    "scipy<1.11",
    "seaborn",
    "sortedcontainers",
    "submitit",
    "temporaldata",
    "torch==2.5.1",
    "torcheval",
    "torchinfo",
    "torchvision==0.20.1",
    "tqdm",
    "typeguard",
    "wandb",
]

[dependency-groups]
dev = [
    "ipdb",
    "ipykernel",
    "jupyter",
    "pyright",
    "pytest",
    "ruff",
]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.uv]
find-links = ["https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"]

[tool.uv.sources]
torch = [
    { index = "pytorch-cu121", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
    { index = "pytorch-cu121", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.ruff]
line-length = 99
target-version = "py39"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]
ignore = [
    "F722",  # Forward declarations used by jaxtyping.
    "E201",  # Whitespace after opening parenthesis.
    "E202",  # Whitespace before closing parenthesis.
    "E203",  # Whitespace before colon.
]

[tool.ruff.lint.isort]
known-third-party = ["wandb"]
